### ISSUE TITLE
UI and i18n issue: 1-3 out of 3 result(s) 

### ISSUE THREAD

**Issue by tabesin** [fossasia/susi.ai#2579]
**Actual Behaviour**

After a query the user interface displays:
1-3 out of 3 result(s) for SUSI Skills All 1 Stars & Up Last 90 days
or
No result found for SUSI Skills:Novelty and Humour

**Expected Behaviour**

A phrase should never mix plural and singular: "result(s)". This needs to be refactored for instance as follows:
**case 0:**
Found no results for xyz
or No result found for <SUSI Skills: Novelty and Humour>
**when 1:**
Found one result for xyz
**case >1:**
1-m out of n results for xyz

Furthermore the mixing of plural and singular makes translations of the interface very complicated.

When there is a **:** you need a space character.

**No result found for SUSI Skills:Novelty and Humour**
becomes
**No result found for SUSI Skills: Novelty and Humour**

**Comment by harsh-jindal** [comment]
Will take this up

**Comment by akshatnitd** [comment]
@harsh-jindal Use `pluralize` npm package for it

**Comment by harsh-jindal** [comment]
@akshatnitd Do you want me to use `pluralize` package for the word `result` ? Because I think that is not required as we have to change the sentence to `Found one result for xyz` for one result and `1-m out of n results for xyz` for more than 1. If we change only the word `result` and use the format `1-m out of n results for xyz` then we can use the `pluralize` npm package.

**Comment by akshatnitd** [comment]
No need to write `one`. Instead display 1. Use pluralise for 'result'
