### ISSUE TITLE
Main page image slider needs improvements.

### ISSUE THREAD

**Issue by tobehonest** [fossasia/susi.ai#3371]
**Actual Behaviour**

The image slider doesn't appeal and the buttons have limited area of clicking. 
If you click above or below another link opens which have possibility of navigating to next/previous images link.

**Expected Behaviour**

Only navigation to the current displayed image or info must be done.

**Steps to reproduce it**

Main page -> try to slide images -> Click on top/botton of the slider

![before](https://user-images.githubusercontent.com/42002993/74598407-0d33be00-5097-11ea-8dc4-e6a2101902da.gif)

**Would you like to work on the issue?**

Yes

**Comment by tobehonest** [comment]
@akshatnitd

**Comment by snitin315** [comment]
@tobehonest please Provide screenshots/GIF in support of your issue.

**Comment by elit-altum** [comment]
@snitin315 @akshatnitd 
The slider-buttons only have a very small clickable area which may cause inconvenience while navigating. They should be changed to full height buttons for ease of navigation.

__Before__
![File-animation-Before](https://user-images.githubusercontent.com/41413622/74593289-cb335980-504f-11ea-860e-402b690b2b5d.gif)


__After (Expected)__
![File-animation-After](https://user-images.githubusercontent.com/41413622/74593302-dc7c6600-504f-11ea-8723-2806b359a440.gif)

__Comments__
I have already implemented the changes in my local code. If the issue is approved I will make a PR. Thank You!

**Comment by tobehonest** [comment]
@akshatnitd Please review if this change is required. Clicking and navigating due in-visible target doesn't seem like actual functionality of the slider.
